package com.indra.iopen.util;

public enum ApplicationAdvanceType {
	INSPECTION_PAID,REINSPECTION_PAID, SITE_INSPECTION, CONNECTION_PENDING, QUOTAION_PREPARED, QUOTATION_PENDING, QUOTATION_SENT, PAID, IN_CONSTRUCTION, CONNECTION_IN_PROGRESS, COMMISIONED, SERVICE_POINT_CREATED, INSPECTION_SCHEDULED, CONNECTION_SCHEDULED, INSPECTION_PASSED, INSPECTION_FAILED;
}
